version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm start'

  caddy:
    image: caddy:2.6
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./app/:/srv
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app